/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#00513b',
        'secondary-container': '#6cf8bb',
        'surface': '#f8f9ff',
        'surface-container-low': '#eef4ff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#002116',
        'inverse-on-surface': '#eaf1ff',
        'tertiary': '#5e3000',
        'secondary-fixed': '#6ffbbe',
        'outline': '#6f7973',
        'on-secondary-container': '#00714d',
        'on-primary-container': '#8bd6b7',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#ffb77d',
        'surface-container-high': '#dfe9fa',
        'on-secondary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#6e3900',
        'primary-container': '#065f46',
        'surface-variant': '#d9e3f4',
        'on-error-container': '#93000a',
        'inverse-primary': '#8bd6b6',
        'secondary-fixed-dim': '#4edea3',
        'surface-tint': '#1b6b51',
        'surface-dim': '#d1dbec',
        'on-tertiary-fixed': '#2f1500',
        'on-tertiary-container': '#ffb87e',
        'primary-fixed-dim': '#8bd6b6',
        'tertiary-container': '#804300',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#ffdcc3',
        'inverse-surface': '#27313e',
        'surface-bright': '#f8f9ff',
        'background': '#f8f9ff',
        'on-error': '#ffffff',
        'error': '#ba1a1a',
        'surface-container': '#e5eeff',
        'primary-fixed': '#a6f2d1',
        'surface-container-highest': '#d9e3f4',
        'secondary': '#006c49',
        'primary': '#004532',
        'on-background': '#121c28',
        'outline-variant': '#bec9c2',
        'on-surface': '#121c28',
        'on-surface-variant': '#3f4944',
        'on-secondary-fixed-variant': '#005236',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};

